development:
  adapter: redis
  url: redis://redis:6379/1
  channel_prefix: event_development

test:
  adapter: redis
  url: redis://redis:6379/2
  channel_prefix: event_test

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: event_production
